export const IPC_CHANNELS = {
  ping: 'app:ping',
  appSetDirty: 'app:setDirty',
  appReportError: 'app:reportError',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  songAssetsAssign: 'songAssets:assign',
  songAssetsAnalyze: 'songAssets:analyze',
  dialogsPickTjaFile: 'dialogs:pickTjaFile',
  setsList: 'sets:list',
  setsCreate: 'sets:create',
  setsLoad: 'sets:load',
  setsSave: 'sets:save',
  setsDelete: 'sets:delete',
  setsDuplicate: 'sets:duplicate',
  setsExportToFolder: 'sets:exportToFolder',
  setsCheckExportFolderConflict: 'sets:checkExportFolderConflict',
  setsExportToZip: 'sets:exportToZip',
  dialogsPickSaveFolder: 'dialogs:pickSaveFolder',
  dialogsPickSaveZip: 'dialogs:pickSaveZip',
  dialogsPickImportFolder: 'dialogs:pickImportFolder',
  dialogsPickImportZip: 'dialogs:pickImportZip',
  dialogsPickFolder: 'dialogs:pickFolder',
  setsImportFromFolder: 'sets:importFromFolder',
  setsImportFromZip: 'sets:importFromZip',
  setsValidate: 'sets:validate'
} as const
